In [1]:
'''
Non Pythonic code
'''

numbers = [1, 2, 3, 4]

double_numbers = []

for i in range(len(numbers)):
    double_numbers.append(numbers[i] * 2)
    
'''
Pythonic
'''
doubled_numbers = [x * 2 for x in numbers]

In [2]:
# the zen of python by Tim Peters
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [3]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

i = 0
new_list = []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
    
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [4]:
# explicitly typing a list of numbers
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(nums)
# use range (start, stop)
nums = range(0, 11)
nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
# range (stop)
nums = range(11)

nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
# using range with a step value
even_nums = range(2, 11, 2)
even_nums_list = list(even_nums)
print(even_nums_list)

[2, 4, 6, 8, 10]


In [7]:
# built in function - enumerate
letters = ['a', 'b', 'c', 'd']

indexed_letters = enumerate(letters)
indexed_letters_list = list(indexed_letters)
print(indexed_letters_list)

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]


In [8]:
indexed_letters2 = enumerate(letters, start=5)

indexed_letters2_list = list(indexed_letters2)
print(indexed_letters2_list)

[(5, 'a'), (6, 'b'), (7, 'c'), (8, 'd')]


In [9]:
# built-in function map()
# applies a function in each element in an object

nums = [1.5, 2.3, 3.4, 4.6, 5.0]
rnd_nums = map(round, nums)
print(list(rnd_nums))

[2, 2, 3, 5, 5]


In [10]:
# built-in function map()
nums = [1, 2, 3, 4]
sqrd_nums = map(lambda x:x ** 2, nums)
print(list(sqrd_nums))

[1, 4, 9, 16]


In [11]:
x = 'hola'
sqrd_nums = map(lambda x:x * 2, x)
print(list(sqrd_nums))

['hh', 'oo', 'll', 'aa']


In [12]:
nums = range(0, 5)
print(type(nums))

# convert nums to a list
nums_list = list(nums)
print(nums_list)

# create a new list of odd numbers from 1 to 11 by unpacking a range object
num_list2 = [list(range(1, 12, 2))]
print(num_list2)

<class 'range'>
[0, 1, 2, 3, 4]
[[1, 3, 5, 7, 9, 11]]


In [13]:
indexed_names = []
for i, name in enumerate(names):
    index_name = (i, name)
    indexed_names.append(index_name)
print(indexed_names)

# rewwrite the above for loop using list comprejension
indexed_names_comp = [(i, name) for i, name in enumerate(names)]
print(indexed_names_comp)
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


In [14]:
# use map to apply str.upper to each element in names
names_map = map(str.upper, names)
print(type(names_map))

<class 'map'>


In [15]:
# unpack anmes_map inot a list
names_uppercase = [*names_map]
# Print the list created above
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [16]:
'''
The power of numpy arrays
'''
nums_list = list(range(5))
print(nums_list)
#
import numpy as np
nums_np = np.array(range(5))
print(nums_np)

[0, 1, 2, 3, 4]
[0 1 2 3 4]


In [17]:
# nupmy arrays are homogenoues, that means they must contains elements of the same type
nums_np_ints = np.array([1, 2, 3])
print(nums_np_ints)
print(nums_np_ints.dtype)

[1 2 3]
int64


In [18]:
nums_np_floats = np.array([1, 2.5, 3])
print(nums_np_floats)
print(nums_np_floats.dtype)

[1.  2.5 3. ]
float64


In [19]:
# the power of numpy arrays
nums2 = [[1, 2, 3],
         [4, 5, 6]]
print(nums2[0][1])
nums2_np = np.array(nums2)
print(nums2_np[0, 1])

2
2


In [20]:
print([row[0] for row in nums2])
print(nums2_np[:,0])

[1, 4]
[1 4]


In [21]:
# np arrays for boolean indexing
nums = [-2, -1, 0, 1, 2]
nums_np = np.array(nums)
print(nums_np > 0)

[False False False  True  True]


In [22]:
print(nums_np[nums_np > 0])

[1 2]


In [23]:
# for loop inefficient option
pos = []
for num in nums:
    if num > 0:
        pos.append(num)
print(pos)

[1, 2]


In [24]:
# list comprehension (better option)
pos = [num for num in nums if num > 0]
print(pos)

[1, 2]


In [25]:
nums = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])
print(nums)
print(nums[1, :])
print(nums[nums > 6])
nums_dbl = nums * 2
print(nums_dbl)
nums[:, 2] = nums[:,2] + 1
print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


In [26]:
arrival_times = [*range(10, 60, 10)]
print(arrival_times)

[10, 20, 30, 40, 50]


In [27]:
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3
print(new_times)

[ 7 17 27 37 47]


In [28]:
# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


In [29]:
def welcome_guest(input_data):
    (guest, time) = input_data
    return 'Welcome to Festivus {} .... You are {} min late'.format(guest, time)

welcome_map = map(welcome_guest, guest_arrivals)

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')
guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

Welcome to Festivus Jerry .... You are 7 min late
Welcome to Festivus Kramer .... You are 17 min late
Welcome to Festivus Elaine .... You are 27 min late
Welcome to Festivus George .... You are 37 min late
Welcome to Festivus Newman .... You are 47 min late



In [30]:
import numpy as np
%timeit rand_nums = np.random.rand(1000)

6.28 µs ± 64.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%timeit -r2 -n10 rand_nums = np.random.rand(1000)

19.1 µs ± 4.56 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


In [32]:
%timeit nums = [x for x in range(10)]

469 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%%timeit
nums = []
for x in range(10):
    nums.append(x)

669 ns ± 7.98 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [34]:
times = %timeit -o rand_nums = np.random.rand(1000)

6.48 µs ± 47.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [35]:
times.timings

[6.492313790000708e-06,
 6.483702289999655e-06,
 6.555307730000095e-06,
 6.47253749000015e-06,
 6.528316729999233e-06,
 6.447055079999018e-06,
 6.399022120000382e-06]

In [36]:
times.best

6.399022120000382e-06

In [37]:
times.worst

6.555307730000095e-06

In [38]:
# python data structures using formal name
formal_list = list()
formal_dict = dict()
formal_tuple = tuple()

# python data structures using literal syntax
literal_list = []
literal_dict = {}
literal_tuple = ()

In [39]:
f_time = %timeit -o formal_dict = dict()


73.2 ns ± 0.657 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [40]:
l_time = %timeit -o literal_dict = {}

28.1 ns ± 0.863 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [41]:
diff = (f_time.average - l_time.average) * (10**9)
print('l_time better than f_time by {} ns'.format(diff))

l_time better than f_time by 45.04297792857089 ns


In [42]:
num_list_comp = [num for num in range(0, 51, 1)]
print(num_list_comp)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [43]:
nums_unpack = [*range(51)]
print(nums_unpack)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [44]:
formal_list = list()
print(formal_list)
literal_list = []
print(literal_list)

[]
[]


In [45]:
%load_ext line_profiler

In [46]:
heroes = ['Batman', 'Superman', 'Wonder Woman']
hts = np.array([188.0, 191.0, 183.0])
wts = np.array([95.0, 101.0, 74.0])

def convert_units(heroes, heights, weights):
    new_hts = [ht * 0.39370 for ht in heights]
    new_wts = [wt * 2.20462 for wt in wts]
    
    hero_data = {}
    
    for i, hero in enumerate(heroes):
        hero_data[hero] = (new_hts[i], new_wts[i])
        
    return hero_data

print(convert_units(heroes, hts, wts))

{'Batman': (74.01559999999999, 209.4389), 'Superman': (75.19669999999999, 222.66661999999997), 'Wonder Woman': (72.0471, 163.14188)}


In [47]:
%timeit convert_units(heroes, hts, wts)

2.69 µs ± 14.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
%lprun -f convert_units  convert_units(heroes, hts, wts)

Timer unit: 1e-06 s

Total time: 1.5e-05 s
File: <ipython-input-46-4c7952b1dec0>
Function: convert_units at line 5

Line #      Hits         Time  Per Hit   % Time  Line Contents
     5                                           def convert_units(heroes, heights, weights):
     6         1         10.0     10.0     66.7      new_hts = [ht * 0.39370 for ht in heights]
     7         1          3.0      3.0     20.0      new_wts = [wt * 2.20462 for wt in wts]
     8                                               
     9         1          0.0      0.0      0.0      hero_data = {}
    10                                               
    11         4          1.0      0.2      6.7      for i, hero in enumerate(heroes):
    12         3          1.0      0.3      6.7          hero_data[hero] = (new_hts[i], new_wts[i])
    13                                                   
    14         1          0.0      0.0      0.0      return hero_data

In [49]:
def convert_units_broadcast(heroes, heights, weights):
    new_hts = heights * 0.39370
    new_wts = weights * 2.20462
    
    hero_data = {}
    
    for i, hero in enumerate(heroes):
        hero_data[hero] = (new_hts[i], new_wts[i])
        
    return hero_data

%lprun -f convert_units_broadcast convert_units_broadcast(heroes, hts, wts)

Timer unit: 1e-06 s

Total time: 8.1e-05 s
File: <ipython-input-49-710df17d2648>
Function: convert_units_broadcast at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def convert_units_broadcast(heroes, heights, weights):
     2         1         39.0     39.0     48.1      new_hts = heights * 0.39370
     3         1         12.0     12.0     14.8      new_wts = weights * 2.20462
     4                                               
     5         1          2.0      2.0      2.5      hero_data = {}
     6                                               
     7         4         12.0      3.0     14.8      for i, hero in enumerate(heroes):
     8         3         14.0      4.7     17.3          hero_data[hero] = (new_hts[i], new_wts[i])
     9                                                   
    10         1          2.0      2.0      2.5      return hero_data

In [50]:
import sys

In [51]:
num_list = [*range(1000)]
sys.getsizeof(num_list)

9120

In [52]:
nums_np = np.array(range(1000))
sys.getsizeof(nums_np)

8096

In [53]:
%load_ext memory_profiler

In [54]:
%mprun -f convert_units convert_units(heroes, hts, wts)

ERROR: Could not find file <ipython-input-46-4c7952b1dec0>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.



In [55]:
from hero_funcs import convert_units as convert_units_file
from hero_funcs import calc_bmi_arrays

In [56]:
!ls

baseball_stats.csv  hero_funcs.py  __pycache__	Pythonic.ipynb


In [57]:
%mprun -f convert_units_file convert_units_file(heroes, hts, wts)

Filename: /home/arturo/Downloads/Writting Efficient Code/hero_funcs.py

Line #    Mem usage    Increment   Line Contents
     4     75.2 MiB     75.2 MiB   def convert_units(heroes, heights, weights):
     5     75.2 MiB      0.0 MiB       new_hts = [ht * 0.39370 for ht in heights]
     6                                 # c
     7     75.2 MiB      0.0 MiB       new_wts = [wt * 2.20462 for wt in weights]
     8                                 
     9     75.2 MiB      0.0 MiB       hero_data = {}
    10                                 
    11     75.2 MiB      0.0 MiB       for i, hero in enumerate(heroes):
    12     75.2 MiB      0.0 MiB           hero_data[hero] = (new_hts[i], new_wts[i])
    13                                     
    14     75.2 MiB      0.0 MiB       return hero_data

In [58]:
# efficiently combining, counting and iterating
names = ['Bulbasaur', 'Charmander', 'Squirtle']
hps = [45, 39, 44]
combined = []

for i, pokemon in enumerate(names):
    combined.append((pokemon, hps[i]))
    
print(combined)

[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]


In [59]:
combined_zip = zip(names, hps)
print(type(combined_zip))
print([*combined_zip])


<class 'zip'>
[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]


In [62]:
poke_types = ['Bug', 'Fire', 'Ghost', 'Grass', 'Water']

# counting with loop
pole_types = []
type_counts = {}

for poke_type in poke_types:
    if poke_type not in type_counts:
        type_counts[poke_type] = 1
    else:
        type_counts[poke_type] += 1
        
print(type_counts)

# use counter from the collections module is a more efficient approach
from collections import Counter

type_counts = Counter(poke_types)
print(type_counts)

{'Bug': 1, 'Fire': 1, 'Ghost': 1, 'Grass': 1, 'Water': 1}
Counter({'Bug': 1, 'Fire': 1, 'Ghost': 1, 'Grass': 1, 'Water': 1})


In [63]:

combos = []

for x in poke_types:
    for y in poke_types:
        if x == y:
            continue
        if ((x, y) not in combos) & ((y, x) not in combos):
            combos.append((x, y))
            
print(combos)

[('Bug', 'Fire'), ('Bug', 'Ghost'), ('Bug', 'Grass'), ('Bug', 'Water'), ('Fire', 'Ghost'), ('Fire', 'Grass'), ('Fire', 'Water'), ('Ghost', 'Grass'), ('Ghost', 'Water'), ('Grass', 'Water')]


In [64]:
from itertools import combinations
combos_obj = combinations(poke_types, 2)
print(type(combos_obj))

<class 'itertools.combinations'>


In [65]:
combos = [*combos_obj]
print(combos)

[('Bug', 'Fire'), ('Bug', 'Ghost'), ('Bug', 'Grass'), ('Bug', 'Water'), ('Fire', 'Ghost'), ('Fire', 'Grass'), ('Fire', 'Water'), ('Ghost', 'Grass'), ('Ghost', 'Water'), ('Grass', 'Water')]


In [66]:
names = ['Abomasnow', 'Abra', 'Absol', 'Accelgor', 'Aerodactyl', 'Aggron', 'Aipom', 'Alakazam', 'Alomomola', 'Altaria', 'Amaura', 'Ambipom', 'Amoonguss', 'Ampharos', 'Anorith', 'Arbok', 'Arcanine', 'Arceus', 'Archen', 'Archeops', 'Ariados', 'Armaldo', 'Aromatisse', 'Aron', 'Articuno', 'Audino', 'Aurorus', 'Avalugg', 'Axew', 'Azelf', 'Azumarill', 'Azurill', 'Bagon', 'Baltoy', 'Banette', 'Barbaracle', 'Barboach', 'Basculin', 'Bastiodon', 'Bayleef', 'Beartic', 'Beautifly', 'Beedrill', 'Beheeyem', 'Beldum', 'Bellossom', 'Bellsprout', 'Bergmite', 'Bibarel', 'Bidoof', 'Binacle', 'Bisharp', 'Blastoise', 'Blaziken', 'Blissey', 'Blitzle', 'Boldore', 'Bonsly', 'Bouffalant', 'Braixen', 'Braviary', 'Breloom', 'Bronzong', 'Bronzor', 'Budew', 'Buizel', 'Bulbasaur', 'Buneary', 'Bunnelby', 'Burmy', 'Butterfree', 'Cacnea', 'Cacturne', 'Camerupt', 'Carbink', 'Carnivine', 'Carracosta', 'Carvanha', 'Cascoon', 'Castform', 'Caterpie', 'Celebi', 'Chandelure', 'Chansey', 'Charizard', 'Charmander', 'Charmeleon', 'Chatot', 'Cherrim', 'Cherubi', 'Chesnaught', 'Chespin', 'Chikorita', 'Chimchar', 'Chimecho', 'Chinchou', 'Chingling', 'Cinccino', 'Clamperl', 'Clauncher', 'Clawitzer', 'Claydol', 'Clefable', 'Clefairy', 'Cleffa', 'Cloyster', 'Cobalion', 'Cofagrigus', 'Combee', 'Combusken', 'Conkeldurr', 'Corphish', 'Corsola', 'Cottonee', 'Cradily', 'Cranidos', 'Crawdaunt', 'Cresselia', 'Croagunk', 'Crobat', 'Croconaw', 'Crustle', 'Cryogonal', 'Cubchoo', 'Cubone', 'Cyndaquil', 'Darkrai', 'DarmanitanStandard Mode', 'DarmanitanZen Mode', 'Darumaka', 'Dedenne', 'Deerling', 'Deino', 'Delcatty', 'Delibird', 'Delphox', 'Dewgong', 'Dewott', 'Dialga', 'Diancie', 'Diggersby', 'Diglett', 'Ditto', 'Dodrio', 'Doduo', 'Donphan', 'Doublade', 'Dragalge', 'Dragonair', 'Dragonite', 'Drapion', 'Dratini', 'Drifblim', 'Drifloon', 'Drilbur', 'Drowzee', 'Druddigon', 'Ducklett', 'Dugtrio', 'Dunsparce', 'Duosion', 'Durant', 'Dusclops', 'Dusknoir', 'Duskull', 'Dustox', 'Dwebble', 'Eelektrik', 'Eelektross', 'Eevee', 'Ekans', 'Electabuzz', 'Electivire', 'Electrike', 'Electrode', 'Elekid', 'Elgyem', 'Emboar', 'Emolga', 'Empoleon', 'Entei', 'Escavalier', 'Espeon', 'Espurr', 'Excadrill', 'Exeggcute', 'Exeggutor', 'Exploud', "Farfetch'd", 'Fearow', 'Feebas', 'Fennekin', 'Feraligatr', 'Ferroseed', 'Ferrothorn', 'Finneon', 'Flaaffy', 'Flabébé', 'Flareon', 'Fletchinder', 'Fletchling', 'Floatzel', 'Floette', 'Florges', 'Flygon', 'Foongus', 'Forretress', 'Fraxure', 'Frillish', 'Froakie', 'Frogadier', 'Froslass', 'Furfrou', 'Furret', 'Gabite', 'Gallade', 'Galvantula', 'Garbodor', 'Garchomp', 'Gardevoir', 'Gastly', 'Gastrodon', 'Genesect', 'Gengar', 'Geodude', 'Gible', 'Gigalith', 'Girafarig', 'Glaceon', 'Glalie', 'Glameow', 'Gligar', 'Gliscor', 'Gloom', 'Gogoat', 'Golbat', 'Goldeen', 'Golduck', 'Golem', 'Golett', 'Golurk', 'Goodra', 'Goomy', 'Gorebyss', 'Gothita', 'Gothitelle', 'Gothorita', 'Granbull', 'Graveler', 'Greninja', 'Grimer', 'Grotle', 'Groudon', 'GroudonPrimal Groudon', 'Grovyle', 'Growlithe', 'Grumpig', 'Gulpin', 'Gurdurr', 'Gyarados', 'Happiny', 'Hariyama', 'Haunter', 'Hawlucha', 'Haxorus', 'Heatmor', 'Heatran', 'Heliolisk', 'Helioptile', 'Heracross', 'Herdier', 'Hippopotas', 'Hippowdon', 'Hitmonchan', 'Hitmonlee', 'Hitmontop', 'Ho-oh', 'Honchkrow', 'Honedge', 'Hoothoot', 'Hoppip', 'Horsea', 'Houndoom', 'Houndour', 'Huntail', 'Hydreigon', 'Hypno', 'Igglybuff', 'Illumise', 'Infernape', 'Inkay', 'Ivysaur', 'Jellicent', 'Jigglypuff', 'Jirachi', 'Jolteon', 'Joltik', 'Jumpluff', 'Jynx', 'Kabuto', 'Kabutops', 'Kadabra', 'Kakuna', 'Kangaskhan', 'Karrablast', 'Kecleon', 'Kingdra', 'Kingler', 'Kirlia', 'Klang', 'Klefki', 'Klink', 'Klinklang', 'Koffing', 'Krabby', 'Kricketot', 'Kricketune', 'Krokorok', 'Krookodile', 'Kyogre', 'KyogrePrimal Kyogre', 'Kyurem', 'KyuremBlack Kyurem', 'KyuremWhite Kyurem', 'Lairon', 'Lampent', 'Lanturn', 'Lapras', 'Larvesta', 'Larvitar', 'Latias', 'Latios', 'Leafeon', 'Leavanny', 'Ledian', 'Ledyba', 'Lickilicky', 'Lickitung', 'Liepard', 'Lileep', 'Lilligant', 'Lillipup', 'Linoone', 'Litleo', 'Litwick', 'Lombre', 'Lopunny', 'Lotad', 'Loudred', 'Lucario', 'Ludicolo', 'Lugia', 'Lumineon', 'Lunatone', 'Luvdisc', 'Luxio', 'Luxray', 'Machamp', 'Machoke', 'Machop', 'Magby', 'Magcargo', 'Magikarp', 'Magmar', 'Magmortar', 'Magnemite', 'Magneton', 'Magnezone', 'Makuhita', 'Malamar', 'Mamoswine', 'Manaphy', 'Mandibuzz', 'Manectric', 'Mankey', 'Mantine', 'Mantyke', 'Maractus', 'Mareep', 'Marill', 'Marowak', 'Marshtomp', 'Masquerain', 'Mawile', 'Medicham', 'Meditite', 'MeowsticFemale', 'MeowsticMale', 'Meowth', 'Mesprit', 'Metagross', 'Metang', 'Metapod', 'Mew', 'Mewtwo', 'Mienfoo', 'Mienshao', 'Mightyena', 'Milotic', 'Miltank', 'Mime Jr.', 'Minccino', 'Minun', 'Misdreavus', 'Mismagius', 'Moltres', 'Monferno', 'Mothim', 'Mr. Mime', 'Mudkip', 'Muk', 'Munchlax', 'Munna', 'Murkrow', 'Musharna', 'Natu', 'Nidoking', 'Nidoqueen', 'Nidoran♀', 'Nidoran♂', 'Nidorina', 'Nidorino', 'Nincada', 'Ninetales', 'Ninjask', 'Noctowl', 'Noibat', 'Noivern', 'Nosepass', 'Numel', 'Nuzleaf', 'Octillery', 'Oddish', 'Omanyte', 'Omastar', 'Onix', 'Oshawott', 'Pachirisu', 'Palkia', 'Palpitoad', 'Pancham', 'Pangoro', 'Panpour', 'Pansage', 'Pansear', 'Paras', 'Parasect', 'Patrat', 'Pawniard', 'Pelipper', 'Persian', 'Petilil', 'Phanpy', 'Phantump', 'Phione', 'Pichu', 'Pidgeot', 'Pidgeotto', 'Pidgey', 'Pidove', 'Pignite', 'Pikachu', 'Piloswine', 'Pineco', 'Pinsir', 'Piplup', 'Plusle', 'Politoed', 'Poliwag', 'Poliwhirl', 'Poliwrath', 'Ponyta', 'Poochyena', 'Porygon', 'Porygon-Z', 'Porygon2', 'Primeape', 'Prinplup', 'Probopass', 'Psyduck', 'Pupitar', 'Purrloin', 'Purugly', 'Pyroar', 'Quagsire', 'Quilava', 'Quilladin', 'Qwilfish', 'Raichu', 'Raikou', 'Ralts', 'Rampardos', 'Rapidash', 'Raticate', 'Rattata', 'Rayquaza', 'Regice', 'Regigigas', 'Regirock', 'Registeel', 'Relicanth', 'Remoraid', 'Reshiram', 'Reuniclus', 'Rhydon', 'Rhyhorn', 'Rhyperior', 'Riolu', 'Roggenrola', 'Roselia', 'Roserade', 'Rotom', 'RotomFan Rotom', 'RotomFrost Rotom', 'RotomHeat Rotom', 'RotomMow Rotom', 'RotomWash Rotom', 'Rufflet', 'Sableye', 'Salamence', 'Samurott', 'Sandile', 'Sandshrew', 'Sandslash', 'Sawk', 'Sawsbuck', 'Scatterbug', 'Sceptile', 'Scizor', 'Scolipede', 'Scrafty', 'Scraggy', 'Scyther', 'Seadra', 'Seaking', 'Sealeo', 'Seedot', 'Seel', 'Seismitoad', 'Sentret', 'Serperior', 'Servine', 'Seviper', 'Sewaddle', 'Sharpedo', 'Shedinja', 'Shelgon', 'Shellder', 'Shellos', 'Shelmet', 'Shieldon', 'Shiftry', 'Shinx', 'Shroomish', 'Shuckle', 'Shuppet', 'Sigilyph', 'Silcoon', 'Simipour', 'Simisage', 'Simisear', 'Skarmory', 'Skiddo', 'Skiploom', 'Skitty', 'Skorupi', 'Skrelp', 'Skuntank', 'Slaking', 'Slakoth', 'Sliggoo', 'Slowbro', 'Slowking', 'Slowpoke', 'Slugma', 'Slurpuff', 'Smeargle', 'Smoochum', 'Sneasel', 'Snivy', 'Snorlax', 'Snorunt', 'Snover', 'Snubbull', 'Solosis', 'Solrock', 'Spearow', 'Spewpa', 'Spheal', 'Spinarak', 'Spinda', 'Spiritomb', 'Spoink', 'Spritzee', 'Squirtle', 'Stantler', 'Staraptor', 'Staravia', 'Starly', 'Starmie', 'Staryu', 'Steelix', 'Stoutland', 'Stunfisk', 'Stunky', 'Sudowoodo', 'Suicune', 'Sunflora', 'Sunkern', 'Surskit', 'Swablu', 'Swadloon', 'Swalot', 'Swampert', 'Swanna', 'Swellow', 'Swinub', 'Swirlix', 'Swoobat', 'Sylveon', 'Taillow', 'Talonflame', 'Tangela', 'Tangrowth', 'Tauros', 'Teddiursa', 'Tentacool', 'Tentacruel', 'Tepig', 'Terrakion', 'Throh', 'Timburr', 'Tirtouga', 'Togekiss', 'Togepi', 'Togetic', 'Torchic', 'Torkoal', 'Torterra', 'Totodile', 'Toxicroak', 'Tranquill', 'Trapinch', 'Treecko', 'Trevenant', 'Tropius', 'Trubbish', 'Turtwig', 'Tympole', 'Tynamo', 'Typhlosion', 'Tyranitar', 'Tyrantrum', 'Tyrogue', 'Tyrunt', 'Umbreon', 'Unfezant', 'Unown', 'Ursaring', 'Uxie', 'Vanillish', 'Vanillite', 'Vanilluxe', 'Vaporeon', 'Venipede', 'Venomoth', 'Venonat', 'Venusaur', 'Vespiquen', 'Vibrava', 'Victini', 'Victreebel', 'Vigoroth', 'Vileplume', 'Virizion', 'Vivillon', 'Volbeat', 'Volcanion', 'Volcarona', 'Voltorb', 'Vullaby', 'Vulpix', 'Wailmer', 'Wailord', 'Walrein', 'Wartortle', 'Watchog', 'Weavile', 'Weedle', 'Weepinbell', 'Weezing', 'Whimsicott', 'Whirlipede', 'Whiscash', 'Whismur', 'Wigglytuff', 'Wingull', 'Wobbuffet', 'Woobat', 'Wooper', 'WormadamPlant Cloak', 'WormadamSandy Cloak', 'WormadamTrash Cloak', 'Wurmple', 'Wynaut', 'Xatu', 'Xerneas', 'Yamask', 'Yanma', 'Yanmega', 'Yveltal', 'Zangoose', 'Zapdos', 'Zebstrika', 'Zekrom', 'Zigzagoon', 'Zoroark', 'Zorua', 'Zubat', 'Zweilous']

In [67]:
primary_types = ['Grass', 'Psychic', 'Dark', 'Bug', 'Rock', 'Steel', 'Normal', 'Psychic', 'Water', 'Dragon', 'Rock', 'Normal', 'Grass', 'Electric', 'Rock', 'Poison', 'Fire', 'Normal', 'Rock', 'Rock', 'Bug', 'Rock', 'Fairy', 'Steel', 'Ice', 'Normal', 'Rock', 'Ice', 'Dragon', 'Psychic', 'Water', 'Normal', 'Dragon', 'Ground', 'Ghost', 'Rock', 'Water', 'Water', 'Rock', 'Grass', 'Ice', 'Bug', 'Bug', 'Psychic', 'Steel', 'Grass', 'Grass', 'Ice', 'Normal', 'Normal', 'Rock', 'Dark', 'Water', 'Fire', 'Normal', 'Electric', 'Rock', 'Rock', 'Normal', 'Fire', 'Normal', 'Grass', 'Steel', 'Steel', 'Grass', 'Water', 'Grass', 'Normal', 'Normal', 'Bug', 'Bug', 'Grass', 'Grass', 'Fire', 'Rock', 'Grass', 'Water', 'Water', 'Bug', 'Normal', 'Bug', 'Psychic', 'Ghost', 'Normal', 'Fire', 'Fire', 'Fire', 'Normal', 'Grass', 'Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Psychic', 'Water', 'Psychic', 'Normal', 'Water', 'Water', 'Water', 'Ground', 'Fairy', 'Fairy', 'Fairy', 'Water', 'Steel', 'Ghost', 'Bug', 'Fire', 'Fighting', 'Water', 'Water', 'Grass', 'Rock', 'Rock', 'Water', 'Psychic', 'Poison', 'Poison', 'Water', 'Bug', 'Ice', 'Ice', 'Ground', 'Fire', 'Dark', 'Fire', 'Fire', 'Fire', 'Electric', 'Normal', 'Dark', 'Normal', 'Ice', 'Fire', 'Water', 'Water', 'Steel', 'Rock', 'Normal', 'Ground', 'Normal', 'Normal', 'Normal', 'Ground', 'Steel', 'Poison', 'Dragon', 'Dragon', 'Poison', 'Dragon', 'Ghost', 'Ghost', 'Ground', 'Psychic', 'Dragon', 'Water', 'Ground', 'Normal', 'Psychic', 'Bug', 'Ghost', 'Ghost', 'Ghost', 'Bug', 'Bug', 'Electric', 'Electric', 'Normal', 'Poison', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Psychic', 'Fire', 'Electric', 'Water', 'Fire', 'Bug', 'Psychic', 'Psychic', 'Ground', 'Grass', 'Grass', 'Normal', 'Normal', 'Normal', 'Water', 'Fire', 'Water', 'Grass', 'Grass', 'Water', 'Electric', 'Fairy', 'Fire', 'Fire', 'Normal', 'Water', 'Fairy', 'Fairy', 'Ground', 'Grass', 'Bug', 'Dragon', 'Water', 'Water', 'Water', 'Ice', 'Normal', 'Normal', 'Dragon', 'Psychic', 'Bug', 'Poison', 'Dragon', 'Psychic', 'Ghost', 'Water', 'Bug', 'Ghost', 'Rock', 'Dragon', 'Rock', 'Normal', 'Ice', 'Ice', 'Normal', 'Ground', 'Ground', 'Grass', 'Grass', 'Poison', 'Water', 'Water', 'Rock', 'Ground', 'Ground', 'Dragon', 'Dragon', 'Water', 'Psychic', 'Psychic', 'Psychic', 'Fairy', 'Rock', 'Water', 'Poison', 'Grass', 'Ground', 'Ground', 'Grass', 'Fire', 'Psychic', 'Poison', 'Fighting', 'Water', 'Normal', 'Fighting', 'Ghost', 'Fighting', 'Dragon', 'Fire', 'Fire', 'Electric', 'Electric', 'Bug', 'Normal', 'Ground', 'Ground', 'Fighting', 'Fighting', 'Fighting', 'Fire', 'Dark', 'Steel', 'Normal', 'Grass', 'Water', 'Dark', 'Dark', 'Water', 'Dark', 'Psychic', 'Normal', 'Bug', 'Fire', 'Dark', 'Grass', 'Water', 'Normal', 'Steel', 'Electric', 'Bug', 'Grass', 'Ice', 'Rock', 'Rock', 'Psychic', 'Bug', 'Normal', 'Bug', 'Normal', 'Water', 'Water', 'Psychic', 'Steel', 'Steel', 'Steel', 'Steel', 'Poison', 'Water', 'Bug', 'Bug', 'Ground', 'Ground', 'Water', 'Water', 'Dragon', 'Dragon', 'Dragon', 'Steel', 'Ghost', 'Water', 'Water', 'Bug', 'Rock', 'Dragon', 'Dragon', 'Grass', 'Bug', 'Bug', 'Bug', 'Normal', 'Normal', 'Dark', 'Rock', 'Grass', 'Normal', 'Normal', 'Fire', 'Ghost', 'Water', 'Normal', 'Water', 'Normal', 'Fighting', 'Water', 'Psychic', 'Water', 'Rock', 'Water', 'Electric', 'Electric', 'Fighting', 'Fighting', 'Fighting', 'Fire', 'Fire', 'Water', 'Fire', 'Fire', 'Electric', 'Electric', 'Electric', 'Fighting', 'Dark', 'Ice', 'Water', 'Dark', 'Electric', 'Fighting', 'Water', 'Water', 'Grass', 'Electric', 'Water', 'Ground', 'Water', 'Bug', 'Steel', 'Fighting', 'Fighting', 'Psychic', 'Psychic', 'Normal', 'Psychic', 'Steel', 'Steel', 'Bug', 'Psychic', 'Psychic', 'Fighting', 'Fighting', 'Dark', 'Water', 'Normal', 'Psychic', 'Normal', 'Electric', 'Ghost', 'Ghost', 'Fire', 'Fire', 'Bug', 'Psychic', 'Water', 'Poison', 'Normal', 'Psychic', 'Dark', 'Psychic', 'Psychic', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Poison', 'Bug', 'Fire', 'Bug', 'Normal', 'Flying', 'Flying', 'Rock', 'Fire', 'Grass', 'Water', 'Grass', 'Rock', 'Rock', 'Rock', 'Water', 'Electric', 'Water', 'Water', 'Fighting', 'Fighting', 'Water', 'Grass', 'Fire', 'Bug', 'Bug', 'Normal', 'Dark', 'Water', 'Normal', 'Grass', 'Ground', 'Ghost', 'Water', 'Electric', 'Normal', 'Normal', 'Normal', 'Normal', 'Fire', 'Electric', 'Ice', 'Bug', 'Bug', 'Water', 'Electric', 'Water', 'Water', 'Water', 'Water', 'Fire', 'Dark', 'Normal', 'Normal', 'Normal', 'Fighting', 'Water', 'Rock', 'Water', 'Rock', 'Dark', 'Normal', 'Fire', 'Water', 'Fire', 'Grass', 'Water', 'Electric', 'Electric', 'Psychic', 'Rock', 'Fire', 'Normal', 'Normal', 'Dragon', 'Ice', 'Normal', 'Rock', 'Steel', 'Water', 'Water', 'Dragon', 'Psychic', 'Ground', 'Ground', 'Ground', 'Fighting', 'Rock', 'Grass', 'Grass', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Normal', 'Dark', 'Dragon', 'Water', 'Ground', 'Ground', 'Ground', 'Fighting', 'Normal', 'Bug', 'Grass', 'Bug', 'Bug', 'Dark', 'Dark', 'Bug', 'Water', 'Water', 'Ice', 'Grass', 'Water', 'Water', 'Normal', 'Grass', 'Grass', 'Poison', 'Bug', 'Water', 'Bug', 'Dragon', 'Water', 'Water', 'Bug', 'Rock', 'Grass', 'Electric', 'Grass', 'Bug', 'Ghost', 'Psychic', 'Bug', 'Water', 'Grass', 'Fire', 'Steel', 'Grass', 'Grass', 'Normal', 'Poison', 'Poison', 'Poison', 'Normal', 'Normal', 'Dragon', 'Water', 'Water', 'Water', 'Fire', 'Fairy', 'Normal', 'Ice', 'Dark', 'Grass', 'Normal', 'Ice', 'Grass', 'Fairy', 'Psychic', 'Rock', 'Normal', 'Bug', 'Ice', 'Bug', 'Normal', 'Ghost', 'Psychic', 'Fairy', 'Water', 'Normal', 'Normal', 'Normal', 'Normal', 'Water', 'Water', 'Steel', 'Normal', 'Ground', 'Poison', 'Rock', 'Water', 'Grass', 'Grass', 'Bug', 'Normal', 'Bug', 'Poison', 'Water', 'Water', 'Normal', 'Ice', 'Fairy', 'Psychic', 'Fairy', 'Normal', 'Fire', 'Grass', 'Grass', 'Normal', 'Normal', 'Water', 'Water', 'Fire', 'Rock', 'Fighting', 'Fighting', 'Water', 'Fairy', 'Fairy', 'Fairy', 'Fire', 'Fire', 'Grass', 'Water', 'Poison', 'Normal', 'Ground', 'Grass', 'Ghost', 'Grass', 'Poison', 'Grass', 'Water', 'Electric', 'Fire', 'Rock', 'Rock', 'Fighting', 'Rock', 'Dark', 'Normal', 'Psychic', 'Normal', 'Psychic', 'Ice', 'Ice', 'Ice', 'Water', 'Bug', 'Bug', 'Bug', 'Grass', 'Bug', 'Ground', 'Psychic', 'Grass', 'Normal', 'Grass', 'Grass', 'Bug', 'Bug', 'Fire', 'Bug', 'Electric', 'Dark', 'Fire', 'Water', 'Water', 'Ice', 'Water', 'Normal', 'Dark', 'Bug', 'Grass', 'Poison', 'Grass', 'Bug', 'Water', 'Normal', 'Normal', 'Water', 'Psychic', 'Psychic', 'Water', 'Bug', 'Bug', 'Bug', 'Bug', 'Psychic', 'Psychic', 'Fairy', 'Ghost', 'Bug', 'Bug', 'Dark', 'Normal', 'Electric', 'Electric', 'Dragon', 'Normal', 'Dark', 'Dark', 'Poison', 'Dark']

In [68]:
#secondary_types =  np.array(['Ice', nan, nan, nan, 'Flying', 'Rock', nan, nan, nan, 'Flying', 'Ice', nan, 'Poison', nan, 'Bug', nan, nan, nan, 'Flying', 'Flying', 'Poison', 'Bug', nan, 'Rock', 'Flying', nan, 'Ice', nan, nan, nan, 'Fairy', 'Fairy', nan, 'Psychic', nan, 'Water', 'Ground', nan, 'Steel', nan, nan, 'Flying', 'Poison', nan, 'Psychic', nan, 'Poison', nan, 'Water', nan, 'Water', 'Steel', nan, 'Fighting', nan, nan, nan, nan, nan, nan, 'Flying', 'Fighting', 'Psychic', 'Psychic', 'Poison', nan, 'Poison', nan, nan, nan, 'Flying', nan, 'Dark', 'Ground', 'Fairy', nan, 'Rock', 'Dark', nan, nan, nan, 'Grass', 'Fire', nan, 'Flying', nan, nan, 'Flying', nan, nan, 'Fighting', nan, nan, nan, nan, 'Electric', nan, nan, nan, nan, nan, 'Psychic', nan, nan, nan, 'Ice', 'Fighting', nan, 'Flying', 'Fighting', nan, nan, 'Rock', 'Fairy', 'Grass', nan, 'Dark', nan, 'Fighting', 'Flying', nan, 'Rock', nan, nan, nan, nan, nan, nan, 'Psychic', nan, 'Fairy', 'Grass', 'Dragon', nan, 'Flying', 'Psychic', 'Ice', nan, 'Dragon', 'Fairy', 'Ground', nan, nan, 'Flying', 'Flying', nan, 'Ghost', 'Dragon', nan, 'Flying', 'Dark', nan, 'Flying', 'Flying', nan, nan, nan, 'Flying', nan, nan, nan, 'Steel', nan, nan, nan, 'Poison', 'Rock', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 'Fighting', 'Flying', 'Steel', nan, 'Steel', nan, nan, 'Steel', 'Psychic', 'Psychic', nan, 'Flying', 'Flying', nan, nan, nan, 'Steel', 'Steel', nan, nan, nan, nan, 'Flying', 'Flying', nan, nan, nan, 'Dragon', 'Poison', 'Steel', nan, 'Ghost', nan, nan, 'Ghost', nan, nan, 'Ground', 'Fighting', 'Electric', nan, 'Ground', 'Fairy', 'Poison', 'Ground', 'Steel', 'Poison', 'Ground', 'Ground', nan, 'Psychic', nan, nan, nan, 'Flying', 'Flying', 'Poison', nan, 'Flying', nan, nan, 'Ground', 'Ghost', 'Ghost', nan, nan, nan, nan, nan, nan, nan, 'Ground', 'Dark', nan, nan, nan, 'Fire', nan, nan, nan, nan, nan, 'Flying', nan, nan, 'Poison', 'Flying', nan, nan, 'Steel', 'Normal', 'Normal', 'Fighting', nan, nan, nan, nan, nan, nan, 'Flying', 'Flying', 'Ghost', 'Flying', 'Flying', nan, 'Fire', 'Fire', nan, 'Dragon', nan, 'Fairy', nan, 'Fighting', 'Psychic', 'Poison', 'Ghost', 'Fairy', 'Psychic', nan, 'Electric', 'Flying', 'Psychic', 'Water', 'Water', nan, 'Poison', nan, nan, nan, 'Dragon', nan, 'Fairy', nan, 'Fairy', nan, nan, nan, nan, nan, nan, 'Dark', 'Dark', nan, nan, 'Ice', 'Ice', 'Ice', 'Rock', 'Fire', 'Electric', 'Ice', 'Fire', 'Ground', 'Psychic', 'Psychic', nan, 'Grass', 'Flying', 'Flying', nan, nan, nan, 'Grass', nan, nan, nan, 'Normal', 'Fire', 'Grass', nan, 'Grass', nan, 'Steel', 'Grass', 'Flying', nan, 'Psychic', nan, nan, nan, nan, nan, nan, nan, 'Rock', nan, nan, nan, 'Steel', 'Steel', 'Steel', nan, 'Psychic', 'Ground', nan, 'Flying', nan, nan, 'Flying', 'Flying', nan, nan, 'Fairy', nan, 'Ground', 'Flying', 'Fairy', 'Psychic', 'Psychic', nan, nan, nan, nan, 'Psychic', 'Psychic', nan, nan, nan, nan, nan, nan, nan, nan, 'Fairy', nan, nan, nan, nan, 'Flying', 'Fighting', 'Flying', 'Fairy', nan, nan, nan, nan, 'Flying', nan, 'Flying', 'Ground', 'Ground', nan, nan, nan, nan, 'Ground', nan, 'Flying', 'Flying', 'Dragon', 'Dragon', nan, 'Ground', 'Dark', nan, 'Poison', 'Water', 'Water', 'Ground', nan, nan, 'Dragon', 'Ground', nan, 'Dark', nan, nan, nan, 'Grass', 'Grass', nan, 'Steel', 'Flying', nan, nan, nan, 'Grass', nan, nan, 'Flying', 'Flying', 'Flying', 'Flying', 'Fighting', nan, 'Ground', nan, nan, nan, nan, nan, nan, nan, 'Fighting', nan, nan, nan, nan, nan, nan, nan, 'Steel', nan, 'Ground', nan, nan, 'Normal', 'Ground', nan, nan, 'Poison', nan, nan, 'Fairy', nan, nan, nan, nan, 'Flying', nan, nan, nan, nan, 'Rock', nan, 'Fire', nan, 'Rock', 'Rock', 'Rock', nan, nan, 'Poison', 'Poison', 'Ghost', 'Flying', 'Ice', 'Fire', 'Grass', 'Water', 'Flying', 'Ghost', 'Flying', nan, 'Dark', nan, nan, nan, 'Grass', nan, nan, 'Steel', 'Poison', 'Fighting', 'Fighting', 'Flying', nan, nan, 'Water', nan, nan, 'Ground', nan, nan, nan, nan, 'Grass', 'Dark', 'Ghost', nan, nan, nan, nan, 'Steel', 'Dark', nan, nan, 'Rock', nan, 'Flying', nan, nan, nan, nan, 'Flying', nan, 'Flying', nan, 'Bug', 'Water', 'Dark', nan, nan, nan, 'Psychic', 'Psychic', 'Psychic', nan, nan, nan, 'Psychic', 'Ice', nan, nan, nan, 'Ice', nan, nan, 'Psychic', 'Flying', nan, 'Water', 'Poison', nan, 'Dark', nan, nan, nan, nan, 'Flying', 'Flying', 'Flying', 'Psychic', nan, 'Ground', nan, 'Electric', 'Dark', nan, nan, nan, nan, 'Water', 'Flying', 'Grass', nan, 'Ground', 'Flying', 'Flying', 'Ground', nan, 'Flying', nan, 'Flying', 'Flying', nan, nan, nan, nan, 'Poison', 'Poison', nan, 'Fighting', nan, nan, 'Rock', 'Flying', nan, 'Flying', nan, nan, 'Ground', nan, 'Fighting', 'Flying', nan, nan, 'Grass', 'Flying', nan, nan, nan, nan, nan, 'Dark', 'Dragon', nan, 'Dragon', nan, 'Flying', nan, nan, nan, nan, nan, nan, nan, 'Poison', 'Poison', 'Poison', 'Poison', 'Flying', 'Dragon', 'Fire', 'Poison', nan, 'Poison', 'Fighting', 'Flying', nan, 'Water', 'Fire', nan, 'Flying', nan, nan, nan, 'Water', nan, nan, 'Ice', 'Poison', 'Poison', nan, 'Fairy', 'Poison', 'Ground', nan, 'Fairy', 'Flying', nan, 'Flying', 'Ground', 'Grass', 'Ground', 'Steel', nan, nan, 'Flying', nan, nan, 'Flying', 'Flying', 'Flying', nan, 'Flying', nan, 'Electric', nan, nan, nan, 'Flying', 'Dragon'])

In [69]:
names_type1 = [*zip(names, primary_types)]

print(*names_type1[:5], sep='\n')

('Abomasnow', 'Grass')
('Abra', 'Psychic')
('Absol', 'Dark')
('Accelgor', 'Bug')
('Aerodactyl', 'Rock')


In [70]:
differing_lengths = [*zip(names[:5], primary_types[:3])]
print(*differing_lengths, sep='\n')

('Abomasnow', 'Grass')
('Abra', 'Psychic')
('Absol', 'Dark')


In [71]:
generations = [1, 1, 1, 5, 3, 5, 1, 6, 1, 6, 5, 5, 4, 6, 3, 4, 2, 5, 2, 5, 4, 1, 1, 2, 6, 5, 5, 6, 6, 1, 4, 5, 6, 2, 6, 1, 3, 2, 4, 1, 5, 3, 5, 5, 1, 5, 5, 5, 5, 6, 1, 3, 4, 6, 1, 4, 5, 3, 5, 5, 1, 4, 1, 1, 5, 6, 5, 1, 1, 6, 5, 5, 4, 6, 1, 1, 4, 5, 4, 5, 6, 2, 3, 5, 6, 5, 3, 4, 5, 1, 5, 6, 1, 1, 2, 3, 3, 3, 4, 4, 1, 3, 6, 3, 5, 3, 5, 3, 3, 1, 3, 6, 4, 4, 4, 5, 3, 4, 4, 3, 5, 5, 3, 5, 4, 1, 1, 3, 5, 3, 2, 5, 4, 3, 2, 4, 3, 5, 3, 1, 2, 4, 3, 5, 3, 5, 4, 1, 2, 4, 3, 5, 5, 1, 4, 6, 3, 6, 3, 4, 1, 5, 6, 1, 5, 4, 4, 3, 3, 5, 2, 3, 1, 6, 5, 1, 5, 4, 3, 6, 1, 3, 3, 6, 4, 3, 5, 4, 2, 4, 4, 1, 2, 5, 1, 3, 6, 4, 1, 1, 1, 1, 2, 4, 1, 1, 4, 4, 5, 3, 1, 4, 5, 3, 4, 1, 3, 4, 2, 5, 3, 4, 1, 1, 1, 5, 1, 4, 4, 3, 4, 3, 5, 3, 2, 3, 3, 3, 2, 4, 1, 3, 4, 2, 6, 5, 2, 5, 5, 1, 1, 1, 5, 4, 2, 4, 2, 2, 5, 5, 5, 4, 2, 3, 3, 5, 4, 5, 6, 3, 1, 2, 4, 2, 5, 1, 4, 3, 1, 1, 1, 1, 3, 5, 1, 3, 3, 3, 3, 5, 2, 5, 4, 2, 2, 3, 6, 4, 2, 1, 2, 5, 5, 3, 1, 3, 5, 5, 5, 5, 6, 5, 1, 5, 1, 5, 5, 1, 6, 4, 3, 1, 6, 5, 1, 4, 6, 5, 1, 2, 5, 5, 3, 1, 5, 5, 3, 3, 3, 6, 1, 5, 1, 3, 3, 4, 5, 3, 1, 1, 1, 6, 3, 3, 4, 5, 3, 5, 4, 5, 1, 5, 5, 3, 5, 6, 5, 4, 5, 6, 1, 1, 4, 1, 3, 4, 1, 4, 1, 1, 5, 4, 4, 5, 5, 6, 1, 1, 2, 4, 2, 5, 2, 5, 5, 6, 1, 3, 3, 5, 6, 4, 3, 3, 1, 5, 5, 2, 3, 5, 3, 6, 3, 5, 2, 1, 2, 5, 2, 3, 3, 1, 3, 1, 1, 4, 3, 1, 3, 5, 1, 3, 6, 4, 5, 2, 2, 6, 2, 2, 5, 6, 2, 1, 3, 5, 3, 3, 5, 5, 5, 3, 5, 2, 2, 4, 4, 3, 5, 6, 1, 4, 1, 1, 4, 2, 3, 4, 5, 2, 4, 3, 3, 4, 3, 3, 3, 3, 1, 2, 3, 5, 5, 6, 4, 3, 5, 5, 5, 6, 1, 2, 3, 1, 5, 6, 2, 1, 3, 5]

In [72]:
type_count = Counter(primary_types)
print(type_count, '\n')

# collect the count of generations
gen_count = Counter(generations)
print(gen_count, '\n')

starting_letters = [name[0] for name in names]

starting_letters_count = Counter(starting_letters)
print(starting_letters_count)

Counter({'Water': 105, 'Normal': 92, 'Bug': 65, 'Grass': 64, 'Fire': 48, 'Psychic': 46, 'Rock': 41, 'Electric': 40, 'Ground': 30, 'Dark': 28, 'Poison': 28, 'Dragon': 25, 'Fighting': 25, 'Ice': 23, 'Steel': 21, 'Ghost': 20, 'Fairy': 17, 'Flying': 2}) 

Counter({5: 122, 3: 103, 1: 99, 4: 78, 2: 51, 6: 47}) 

Counter({'S': 102, 'M': 58, 'C': 55, 'P': 47, 'G': 46, 'D': 41, 'B': 39, 'T': 35, 'L': 33, 'A': 32, 'R': 30, 'H': 27, 'F': 26, 'K': 25, 'W': 23, 'V': 22, 'E': 21, 'N': 16, 'Z': 9, 'J': 7, 'O': 6, 'I': 5, 'U': 5, 'Q': 4, 'Y': 4, 'X': 2})


In [74]:
from itertools import combinations

pokemon = ['Geodude', 'Cubone', 'Lickitung', 'Persian', 'Diglett']

combos_obj = combinations(pokemon, 2)
print(type(combos_obj), '\n')

combos_2 = [*combos_obj]
print(combos_2, '\n')

combos_4 = [*combinations(pokemon, 4)]
print(combos_4)

<class 'itertools.combinations'> 

[('Geodude', 'Cubone'), ('Geodude', 'Lickitung'), ('Geodude', 'Persian'), ('Geodude', 'Diglett'), ('Cubone', 'Lickitung'), ('Cubone', 'Persian'), ('Cubone', 'Diglett'), ('Lickitung', 'Persian'), ('Lickitung', 'Diglett'), ('Persian', 'Diglett')] 

[('Geodude', 'Cubone', 'Lickitung', 'Persian'), ('Geodude', 'Cubone', 'Lickitung', 'Diglett'), ('Geodude', 'Cubone', 'Persian', 'Diglett'), ('Geodude', 'Lickitung', 'Persian', 'Diglett'), ('Cubone', 'Lickitung', 'Persian', 'Diglett')]


In [76]:
list_a = ['Bulbasaur', 'Charmander', 'Squirtle']
list_b = ['Caterpie', 'Pidgey', 'Squirtle']

in_common = []

for pokemon_a in list_a:
    for pokemon_b in list_b:
        if pokemon_a == pokemon_b:
            in_common.append(pokemon_a)
            
print(in_common)

['Squirtle']


In [77]:
set_a = set(list_a)
print(set_a)
set_b = set(list_b)
print(set_b)
print(set_a.intersection(set_b))

{'Bulbasaur', 'Squirtle', 'Charmander'}
{'Pidgey', 'Squirtle', 'Caterpie'}
{'Squirtle'}


In [79]:
%%timeit
in_common = []

for pokemon_a in list_a:
    for pokemon_b in list_b:
        if pokemon_a == pokemon_b:
            in_common.append(pokemon_a)

384 ns ± 3.98 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [80]:
%timeit in_common = set_a.intersection(set_b)

110 ns ± 1.89 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [81]:
set_a.difference(set_b)

{'Bulbasaur', 'Charmander'}

In [82]:
set_b.difference(set_a)

{'Caterpie', 'Pidgey'}

In [83]:
set_a.symmetric_difference(set_b)

{'Bulbasaur', 'Caterpie', 'Charmander', 'Pidgey'}

In [85]:
set_a.union(set_b)

{'Bulbasaur', 'Caterpie', 'Charmander', 'Pidgey', 'Squirtle'}

In [88]:
names_list = names
#names_dict = {names}
names_set = set(names)

print(type(names_list))
#print(type(names_dict))
print(type(names_set))

<class 'list'>
<class 'set'>


In [89]:
%timeit 'Zubat' in names_list

7.25 µs ± 79 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [90]:
%timeit 'Zubat' in names_set

25.4 ns ± 0.291 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [91]:
# set is a collection of distinct elements

In [93]:
unique_types = []

for prim_type in primary_types:
    if prim_type not in unique_types:
        unique_types.append(prim_type)
        
print(unique_types)

['Grass', 'Psychic', 'Dark', 'Bug', 'Rock', 'Steel', 'Normal', 'Water', 'Dragon', 'Electric', 'Poison', 'Fire', 'Fairy', 'Ice', 'Ground', 'Ghost', 'Fighting', 'Flying']


In [95]:
ash_pokedex = ['Pikachu', 'Bulbasaur', 'Koffing', 'Spearow', 'Vulpix', 'Wigglytuff', 'Zubat', 'Rattata', 'Psyduck', 'Squirtle']
misty_pokedex = ['Krabby', 'Horsea', 'Slowbro', 'Tentacool', 'Vaporeon', 'Magikarp', 'Poliwag', 'Starmie', 'Psyduck', 'Squirtle']

ash_set = set(ash_pokedex)
misty_set = set(misty_pokedex)

both = ash_set.intersection(misty_set)
print(both)

ash_only = ash_set.difference(misty_set)
print(ash_only)

unique_to_set = ash_set.symmetric_difference(misty_set)
print(unique_to_set)

{'Psyduck', 'Squirtle'}
{'Wigglytuff', 'Vulpix', 'Spearow', 'Rattata', 'Bulbasaur', 'Koffing', 'Pikachu', 'Zubat'}
{'Slowbro', 'Vulpix', 'Wigglytuff', 'Starmie', 'Vaporeon', 'Spearow', 'Krabby', 'Rattata', 'Poliwag', 'Bulbasaur', 'Koffing', 'Horsea', 'Magikarp', 'Pikachu', 'Zubat', 'Tentacool'}


In [96]:
brock_pokedex = ['Onix', 'Geodude', 'Zubat', 'Golem', 'Vulpix', 'Tauros', 'Kabutops', 'Omastar', 'Machop', 'Dugtrio']

In [98]:
brock_pokedex_set = set(brock_pokedex)
print(brock_pokedex_set)

{'Kabutops', 'Geodude', 'Vulpix', 'Tauros', 'Golem', 'Onix', 'Omastar', 'Dugtrio', 'Zubat', 'Machop'}


In [99]:
print('Psyduck' in ash_pokedex)
print('Psyduck' in brock_pokedex_set)

True
False


In [100]:
print('Machop' in ash_pokedex)
print('Machop' in brock_pokedex_set)

False
True


In [101]:
uniq_names_func = set(names)
print(len(names))
print(len(uniq_names_func))

720
720


In [105]:
from collections import Counter
gen_counts = Counter(generations)

total_count = len(generations)

for gen, count in gen_counts.items():
    gen_percent = round(count / total_count * 100, 2)
    print('generations {}: count= {:3} percentage= {}'.format(
        gen, count, gen_percent))

generations 1: count=  99 percentage= 19.8
generations 5: count= 122 percentage= 24.4
generations 3: count= 103 percentage= 20.6
generations 6: count=  47 percentage= 9.4
generations 4: count=  78 percentage= 15.6
generations 2: count=  51 percentage= 10.2
